site_name: 缠中说禅
theme:
  font: false
  name: material
  palette:
    primary: black
    accent: white
  language: zh
  features:
    - navigation.top
    - toc.integrate
plugins:
  - search:
      prebuild_index: true
      lang: ja
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true